print ("Bem vindo! Para continuar digite os dados solicitados abaixo")
numero1 = int ( input ("Digite um numero inteiro: "))
numero2 = int ( input ("Digite outro numero inteiro: "))
numero3 = int ( input ("Digite um numero real: "))
print (f"O produto do dobro do primeiro com a metade do segundo é: {float ((numero1 * 2) + (numero2 / 2))}")
print (f"A soma do triplo do primeiro mais o terceiro é: {(numero1 * 3) + numero3 }")
print (f"O terceiro elevado ao cubo é: { numero3 ** 3}")
print ("Obrigado pela participação!")